name = "GeneralizedCRT"
uuid = "7208565e-50fc-4253-9db2-a2925814c645"
authors = ["Klaus Crusius <klaus.crusius@web.de> and contributors"]
version = "0.1.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
Primes = "< 1"
julia = "1"
